CC = g++
FLAGS = -std=c++11 -Wall -Werror -Wno-sign-compare -Wno-unused-result
CPP = main.cpp Rectangle.cpp Quadrate.cpp Trapeze.cpp
NAME = main

all:
	$(CC) $(FLAGS) -o $(NAME) $(CPP)

clean:
	rm -f *.o $(NAME)